// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQDNIIyUi_BkNCqNmeuvSVhv_cxopiiPs',
    appId: '1:666814214352:web:4a51fb6823b8f91b09eed5',
    messagingSenderId: '666814214352',
    projectId: 'logincamara-fcm',
    authDomain: 'logincamara-fcm.firebaseapp.com',
    storageBucket: 'logincamara-fcm.firebasestorage.app',
    measurementId: 'G-8YWB70DGXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw2BlHg_LDMiMTNnwGlmjSE4aPrSfeB9E',
    appId: '1:666814214352:android:7ee4e17a7cc02f7809eed5',
    messagingSenderId: '666814214352',
    projectId: 'logincamara-fcm',
    storageBucket: 'logincamara-fcm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH2XYGlqvkujMCwDZtv3BZUvSqrJQG9lo',
    appId: '1:666814214352:ios:f957e010ac22983009eed5',
    messagingSenderId: '666814214352',
    projectId: 'logincamara-fcm',
    storageBucket: 'logincamara-fcm.firebasestorage.app',
    iosBundleId: 'com.example.logincamara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH2XYGlqvkujMCwDZtv3BZUvSqrJQG9lo',
    appId: '1:666814214352:ios:f957e010ac22983009eed5',
    messagingSenderId: '666814214352',
    projectId: 'logincamara-fcm',
    storageBucket: 'logincamara-fcm.firebasestorage.app',
    iosBundleId: 'com.example.logincamara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQDNIIyUi_BkNCqNmeuvSVhv_cxopiiPs',
    appId: '1:666814214352:web:50a18cc23dcdc8f809eed5',
    messagingSenderId: '666814214352',
    projectId: 'logincamara-fcm',
    authDomain: 'logincamara-fcm.firebaseapp.com',
    storageBucket: 'logincamara-fcm.firebasestorage.app',
    measurementId: 'G-K4EE6JD4E3',
  );
}
